# Generated by Django 2.1.7 on 2019-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='movie_pics'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='people_pics'),
        ),
    ]
