# Generated by Django 2.1.7 on 2019-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190419_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
