# Generated by Django 2.1.7 on 2019-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190419_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='movie_pics/default.jpg', upload_to='movie_pics'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(default='people_pics/default.jpg', upload_to='people_pics'),
        ),
    ]
