# Generated by Django 2.1.7 on 2019-04-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190419_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='introduction',
        ),
    ]
