# Generated by Django 2.1.7 on 2019-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190419_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='movie_pics/default.jpg', upload_to='movie_pics'),
        ),
        migrations.AddField(
            model_name='movies',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
