# Generated by Django 2.1.7 on 2019-04-19 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0007_auto_20190419_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
        migrations.AddField(
            model_name='movies',
            name='favorite_by',
            field=models.ManyToManyField(related_name='movie_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, default='movie_pics/default.jpg', upload_to='movie_pics'),
        ),
    ]
