# Generated by Django 2.1.7 on 2019-04-19 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190419_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='movie_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='movie_pics/default.jpg', upload_to='movie_pics'),
        ),
    ]
