# Generated by Django 2.1.7 on 2019-04-19 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20190419_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
