# Generated by Django 2.1.7 on 2019-04-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190419_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='deathYear',
        ),
    ]
