# Generated by Django 2.1.7 on 2019-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190419_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/Default.jpg', upload_to='profile_image'),
        ),
    ]
