# Generated by Django 2.1.7 on 2019-04-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190419_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_actors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.People'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movies'),
        ),
    ]
